# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7c8ec8ee066e9710a5f2f0ac32b96338f28e0b312dd299a5ef25ec3af41251da9134c9e5d67d3b8ab5aa3dcfd550bce72ba295466b185a7d07c604fd9122bb

test:
  secret_key_base: fb83990b58013de678a7017b0ef48eae0c786ce9d364d7427ee4229da1c64d0c711fd95a6138246009689fcd6370d7d70679dfb0d65c32f4c6f454efd7de1664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
